package country

import (
	"survey-backend/internal/country/response"

	"gorm.io/gorm"
)

type Country struct {
	gorm.Model
	Name   string `gorm:"uniqueIndex;size:100;not null" json:"name"`
	Code   string `gorm:"uniqueIndex;size:3;not null" json:"code"`
	Active bool   `gorm:"default:false" json:"active"`
}

// GetAllCountries returns all countries for seeding
func GetAllCountries() []Country {
	return []Country{
		{Name: "Afghanistan", Code: "AFG"},
		{Name: "Albania", Code: "ALB"},
		{Name: "Algeria", Code: "DZA"},
		{Name: "Andorra", Code: "AND"},
		{Name: "Angola", Code: "AGO"},
		{Name: "Antigua and Barbuda", Code: "ATG"},
		{Name: "Argentina", Code: "ARG"},
		{Name: "Armenia", Code: "ARM"},
		{Name: "Australia", Code: "AUS"},
		{Name: "Austria", Code: "AUT"},
		{Name: "Azerbaijan", Code: "AZE"},
		{Name: "Bahamas", Code: "BHS"},
		{Name: "Bahrain", Code: "BHR"},
		{Name: "Bangladesh", Code: "BGD"},
		{Name: "Barbados", Code: "BRB"},
		{Name: "Belarus", Code: "BLR"},
		{Name: "Belgium", Code: "BEL"},
		{Name: "Belize", Code: "BLZ"},
		{Name: "Benin", Code: "BEN"},
		{Name: "Bhutan", Code: "BTN"},
		{Name: "Bolivia", Code: "BOL"},
		{Name: "Bosnia and Herzegovina", Code: "BIH"},
		{Name: "Botswana", Code: "BWA"},
		{Name: "Brazil", Code: "BRA"},
		{Name: "Brunei", Code: "BRN"},
		{Name: "Bulgaria", Code: "BGR"},
		{Name: "Burkina Faso", Code: "BFA"},
		{Name: "Burundi", Code: "BDI"},
		{Name: "Cabo Verde", Code: "CPV"},
		{Name: "Cambodia", Code: "KHM"},
		{Name: "Cameroon", Code: "CMR"},
		{Name: "Canada", Code: "CAN"},
		{Name: "Central African Republic", Code: "CAF"},
		{Name: "Chad", Code: "TCD"},
		{Name: "Chile", Code: "CHL"},
		{Name: "China", Code: "CHN"},
		{Name: "Colombia", Code: "COL"},
		{Name: "Comoros", Code: "COM"},
		{Name: "Congo", Code: "COG"},
		{Name: "Costa Rica", Code: "CRI"},
		{Name: "Croatia", Code: "HRV"},
		{Name: "Cuba", Code: "CUB"},
		{Name: "Cyprus", Code: "CYP"},
		{Name: "Czech Republic", Code: "CZE"},
		{Name: "Denmark", Code: "DNK"},
		{Name: "Djibouti", Code: "DJI"},
		{Name: "Dominica", Code: "DMA"},
		{Name: "Dominican Republic", Code: "DOM"},
		{Name: "Ecuador", Code: "ECU"},
		{Name: "Egypt", Code: "EGY"},
		{Name: "El Salvador", Code: "SLV"},
		{Name: "Equatorial Guinea", Code: "GNQ"},
		{Name: "Eritrea", Code: "ERI"},
		{Name: "Estonia", Code: "EST"},
		{Name: "Eswatini", Code: "SWZ"},
		{Name: "Ethiopia", Code: "ETH"},
		{Name: "Fiji", Code: "FJI"},
		{Name: "Finland", Code: "FIN"},
		{Name: "France", Code: "FRA"},
		{Name: "Gabon", Code: "GAB"},
		{Name: "Gambia", Code: "GMB"},
		{Name: "Georgia", Code: "GEO"},
		{Name: "Germany", Code: "DEU"},
		{Name: "Ghana", Code: "GHA"},
		{Name: "Greece", Code: "GRC"},
		{Name: "Grenada", Code: "GRD"},
		{Name: "Guatemala", Code: "GTM"},
		{Name: "Guinea", Code: "GIN"},
		{Name: "Guinea-Bissau", Code: "GNB"},
		{Name: "Guyana", Code: "GUY"},
		{Name: "Haiti", Code: "HTI"},
		{Name: "Honduras", Code: "HND"},
		{Name: "Hungary", Code: "HUN"},
		{Name: "Iceland", Code: "ISL"},
		{Name: "India", Code: "IND"},
		{Name: "Indonesia", Code: "IDN"},
		{Name: "Iran", Code: "IRN"},
		{Name: "Iraq", Code: "IRQ"},
		{Name: "Ireland", Code: "IRL"},
		{Name: "Israel", Code: "ISR"},
		{Name: "Italy", Code: "ITA"},
		{Name: "Jamaica", Code: "JAM"},
		{Name: "Japan", Code: "JPN"},
		{Name: "Jordan", Code: "JOR"},
		{Name: "Kazakhstan", Code: "KAZ"},
		{Name: "Kenya", Code: "KEN"},
		{Name: "Kiribati", Code: "KIR"},
		{Name: "Korea, North", Code: "PRK"},
		{Name: "Korea, South", Code: "KOR"},
		{Name: "Kosovo", Code: "XKX"},
		{Name: "Kuwait", Code: "KWT"},
		{Name: "Kyrgyzstan", Code: "KGZ"},
		{Name: "Laos", Code: "LAO"},
		{Name: "Latvia", Code: "LVA"},
		{Name: "Lebanon", Code: "LBN"},
		{Name: "Lesotho", Code: "LSO"},
		{Name: "Liberia", Code: "LBR"},
		{Name: "Libya", Code: "LBY"},
		{Name: "Liechtenstein", Code: "LIE"},
		{Name: "Lithuania", Code: "LTU"},
		{Name: "Luxembourg", Code: "LUX"},
		{Name: "Madagascar", Code: "MDG"},
		{Name: "Malawi", Code: "MWI"},
		{Name: "Malaysia", Code: "MYS"},
		{Name: "Maldives", Code: "MDV"},
		{Name: "Mali", Code: "MLI"},
		{Name: "Malta", Code: "MLT"},
		{Name: "Marshall Islands", Code: "MHL"},
		{Name: "Mauritania", Code: "MRT"},
		{Name: "Mauritius", Code: "MUS"},
		{Name: "Mexico", Code: "MEX"},
		{Name: "Micronesia", Code: "FSM"},
		{Name: "Moldova", Code: "MDA"},
		{Name: "Monaco", Code: "MCO"},
		{Name: "Mongolia", Code: "MNG"},
		{Name: "Montenegro", Code: "MNE"},
		{Name: "Morocco", Code: "MAR"},
		{Name: "Mozambique", Code: "MOZ"},
		{Name: "Myanmar", Code: "MMR"},
		{Name: "Namibia", Code: "NAM"},
		{Name: "Nauru", Code: "NRU"},
		{Name: "Nepal", Code: "NPL"},
		{Name: "Netherlands", Code: "NLD"},
		{Name: "New Zealand", Code: "NZL"},
		{Name: "Nicaragua", Code: "NIC"},
		{Name: "Niger", Code: "NER"},
		{Name: "Nigeria", Code: "NGA"},
		{Name: "North Macedonia", Code: "MKD"},
		{Name: "Norway", Code: "NOR"},
		{Name: "Oman", Code: "OMN"},
		{Name: "Pakistan", Code: "PAK"},
		{Name: "Palau", Code: "PLW"},
		{Name: "Palestine", Code: "PSE"},
		{Name: "Panama", Code: "PAN"},
		{Name: "Papua New Guinea", Code: "PNG"},
		{Name: "Paraguay", Code: "PRY"},
		{Name: "Peru", Code: "PER"},
		{Name: "Philippines", Code: "PHL"},
		{Name: "Poland", Code: "POL"},
		{Name: "Portugal", Code: "PRT"},
		{Name: "Qatar", Code: "QAT"},
		{Name: "Romania", Code: "ROU"},
		{Name: "Russia", Code: "RUS"},
		{Name: "Rwanda", Code: "RWA"},
		{Name: "Saint Kitts and Nevis", Code: "KNA"},
		{Name: "Saint Lucia", Code: "LCA"},
		{Name: "Saint Vincent and the Grenadines", Code: "VCT"},
		{Name: "Samoa", Code: "WSM"},
		{Name: "San Marino", Code: "SMR"},
		{Name: "Sao Tome and Principe", Code: "STP"},
		{Name: "Saudi Arabia", Code: "SAU"},
		{Name: "Senegal", Code: "SEN"},
		{Name: "Serbia", Code: "SRB"},
		{Name: "Seychelles", Code: "SYC"},
		{Name: "Sierra Leone", Code: "SLE"},
		{Name: "Singapore", Code: "SGP"},
		{Name: "Slovakia", Code: "SVK"},
		{Name: "Slovenia", Code: "SVN"},
		{Name: "Solomon Islands", Code: "SLB"},
		{Name: "Somalia", Code: "SOM"},
		{Name: "South Africa", Code: "ZAF"},
		{Name: "South Sudan", Code: "SSD"},
		{Name: "Spain", Code: "ESP"},
		{Name: "Sri Lanka", Code: "LKA"},
		{Name: "Sudan", Code: "SDN"},
		{Name: "Suriname", Code: "SUR"},
		{Name: "Sweden", Code: "SWE"},
		{Name: "Switzerland", Code: "CHE"},
		{Name: "Syria", Code: "SYR"},
		{Name: "Taiwan", Code: "TWN"},
		{Name: "Tajikistan", Code: "TJK"},
		{Name: "Tanzania", Code: "TZA"},
		{Name: "Thailand", Code: "THA"},
		{Name: "Timor-Leste", Code: "TLS"},
		{Name: "Togo", Code: "TGO"},
		{Name: "Tonga", Code: "TON"},
		{Name: "Trinidad and Tobago", Code: "TTO"},
		{Name: "Tunisia", Code: "TUN"},
		{Name: "Turkey", Code: "TUR"},
		{Name: "Turkmenistan", Code: "TKM"},
		{Name: "Tuvalu", Code: "TUV"},
		{Name: "Uganda", Code: "UGA"},
		{Name: "Ukraine", Code: "UKR"},
		{Name: "United Arab Emirates", Code: "ARE"},
		{Name: "United Kingdom", Code: "GBR"},
		{Name: "United States", Code: "USA"},
		{Name: "Uruguay", Code: "URY"},
		{Name: "Uzbekistan", Code: "UZB"},
		{Name: "Vanuatu", Code: "VUT"},
		{Name: "Vatican City", Code: "VAT"},
		{Name: "Venezuela", Code: "VEN"},
		{Name: "Vietnam", Code: "VNM"},
		{Name: "Yemen", Code: "YEM"},
		{Name: "Zambia", Code: "ZMB"},
		{Name: "Zimbabwe", Code: "ZWE"},
	}
}

// Converts Country model to API response
func (c Country) ToResponse() response.CountryResponse {
	return response.CountryResponse{
		ID:   c.ID,
		Name: c.Name,
		Code: c.Code,
	}
}
